
language: python
python:
  - "2.7"
os:
  - linux
env:
  global:
    - IDE_VERSION=1.8.5
matrix: 
  include:
  - env:
      - NAME= arduinoCI
    python:
      - "3.6"
    install: 
    #Install Arduino IDE
      - mkdir -p $HOME/IDE/arduino
      - cd $HOME/IDE
      - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz #Downloading Arduino IDE from arduino.cc
      - tar xf arduino-$IDE_VERSION-linux64.tar.xz #Extracting Arduino IDE
      - mv ./arduino-$IDE_VERSION/* ./arduino
      - rm arduino-$IDE_VERSION-linux64.tar.xz #Remove tar folder  
    #Install STM32duino Core
      - cd ./arduino/
      - ./arduino --save-prefs --pref "boardsmanager.additional.urls=https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json"
      - ./arduino --install-boards STM32:stm32
      - cd $HOME/.arduino15/packages/STM32/hardware/stm32/*
      - core_version=${PWD##*/}
      - rm -r $HOME/.arduino15/packages/STM32/hardware/stm32/$core_version/
      - cd $HOME/.arduino15/packages/STM32/hardware/stm32/
      - sudo ln -s $TRAVIS_BUILD_DIR
      - ls $HOME/.arduino15/packages/STM32/hardware/stm32/
    before_script:
      - cd $TRAVIS_BUILD_DIR
      - cp $TRAVIS_BUILD_DIR/CI/conf/config-travis.json  $TRAVIS_BUILD_DIR/config.json
    script: 
      - python arduino-builder.py --travis -b blue -s blINk

after_failure:
  - echo " The build is failed. If script return a non-zero return status , we suggest you to take the above logs into consideration. Otherwise, consult the TRAVIS CI documentation to learn more about build failure" 
