
language: python
python:
  - "3.6"
os:
  - linux
env:
  global:
    - IDE_VERSION=1.8.5
matrix: 
  include:
  - env:
      - NAME= arduinoCI
      - ARDUINO_IDE_PATH=$HOME/IDE/arduino
    install: 
    #Install Arduino IDE
      - mkdir -p $ARDUINO_IDE_PATH
      - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz #Downloading Arduino IDE from arduino.cc
      - tar xf arduino-$IDE_VERSION-linux64.tar.xz --strip-components=1 -C $ARDUINO_IDE_PATH #Extracting Arduino IDE
      - rm arduino-$IDE_VERSION-linux64.tar.xz #Remove tar folder  
    #Install STM32duino Core
      - cd $ARDUINO_IDE_PATH
      - ./arduino --save-prefs --pref "boardsmanager.additional.urls=https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json"
      - ./arduino --install-boards STM32:stm32
      - rm -fr $HOME/.arduino15/packages/STM32/hardware/stm32/*
      - sudo ln -s $TRAVIS_BUILD_DIR $HOME/.arduino15/packages/STM32/hardware/stm32/*
      - ls $HOME/.arduino15/packages/STM32/hardware/stm32/*
    before_script:
      - cd $TRAVIS_BUILD_DIR/CI/build/
      - cp ./conf/path_config_travis.json ./path_config.json
    script: 
      - python arduino-builder.py --travis

after_failure:
  - echo " The build is failed. If script return a non-zero return status , we suggest you to take the above logs into consideration. Otherwise, consult the TRAVIS CI documentation to learn more about build failure" 
